using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace NexoMarket.SuperAdmin
{
    public sealed class MainForm : Form
    {
        private readonly ApiClient _api=new ApiClient();
        private TextBox _url,_key,_trialDays,_newStoreName,_newEmail,_newPassword,_newOwner,_newCategory;
        private Label _status,_storesCount,_accountsCount,_activeCount;
        private DataGridView _stores,_accounts;
        private Button _connect;
        private Color bg=Color.FromArgb(10,13,18), panel=Color.FromArgb(18,23,31), line=Color.FromArgb(39,50,64), green=Color.FromArgb(57,255,102), text=Color.White, muted=Color.FromArgb(150,165,180);
        public MainForm()
        {
            Text="NexoMarket · Super Administrador"; Width=1280; Height=820; MinimumSize=new Size(1050,700); StartPosition=FormStartPosition.CenterScreen; BackColor=bg; ForeColor=text;
            try{Icon=new Icon(Application.StartupPath+"\\Assets\\NexoMarket.ico");}catch{}
            Build();
        }
        private Label L(string t,int size=10){return new Label{Text=t,AutoSize=true,ForeColor=muted,Font=new Font("Segoe UI",size,FontStyle.Regular)};}
        private TextBox T(int w=220){return new TextBox{Width=w,BackColor=Color.FromArgb(12,16,22),ForeColor=text,BorderStyle=BorderStyle.FixedSingle,Font=new Font("Segoe UI",10)};}
        private Button B(string t){var b=new Button{Text=t,AutoSize=true,Height=34,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(25,34,44),ForeColor=text,Font=new Font("Segoe UI",9,FontStyle.Bold),Padding=new Padding(12,4,12,4)};b.FlatAppearance.BorderColor=line;b.FlatAppearance.MouseOverBackColor=Color.FromArgb(32,45,56);return b;}
        private Panel Card(){return new Panel{BackColor=panel,BorderStyle=BorderStyle.FixedSingle,Padding=new Padding(14),Margin=new Padding(8)};}
        private void Build()
        {
            var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=4,ColumnCount=1,BackColor=bg};root.RowStyles.Add(new RowStyle(SizeType.Absolute,74));root.RowStyles.Add(new RowStyle(SizeType.Absolute,88));root.RowStyles.Add(new RowStyle(SizeType.Absolute,92));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));Controls.Add(root);
            var header=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(7,9,13),Padding=new Padding(20,12,20,8)};root.Controls.Add(header,0,0);
            var brand=new Label{Text="NEXO",ForeColor=green,Font=new Font("Segoe UI",24,FontStyle.Bold),AutoSize=true,Location=new Point(20,13)};header.Controls.Add(brand);var brand2=new Label{Text="MARKET",ForeColor=text,Font=new Font("Segoe UI",24,FontStyle.Bold),AutoSize=true,Location=new Point(112,13)};header.Controls.Add(brand2);header.Controls.Add(new Label{Text="SUPER ADMINISTRADOR · CONTROL TOTAL",ForeColor=muted,Font=new Font("Segoe UI",9,FontStyle.Bold),AutoSize=true,Location=new Point(270,28)});
            var conn=new FlowLayoutPanel{Dock=DockStyle.Right,Width=600,FlowDirection=FlowDirection.LeftToRight,WrapContents=false,Padding=new Padding(0,18,0,0)};header.Controls.Add(conn);_url=T(270);_url.Text="https://nexomarket-0k22.onrender.com";_key=T(210);_key.UseSystemPasswordChar=true;_connect=B("CONECTAR");_connect.BackColor=Color.FromArgb(40,120,70);_connect.Click+=(s,e)=>RefreshAll();conn.Controls.Add(_url);conn.Controls.Add(_key);conn.Controls.Add(_connect);
            var stats=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1};for(int i=0;i<3;i++)stats.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.33f));root.Controls.Add(stats,0,1);_storesCount=Stat(stats,"TIENDAS",0);_accountsCount=Stat(stats,"CUENTAS",1);_activeCount=Stat(stats,"TIENDAS ACTIVAS",2);
            var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(10,12,10,10),BackColor=bg};root.Controls.Add(actions,0,2);
            var create=B("＋ NUEVA TIENDA");create.Click+=(s,e)=>CreateStoreDialog();actions.Controls.Add(create);
            var trial=B("ASIGNAR PRUEBA");trial.Click+=(s,e)=>AssignTrial();actions.Controls.Add(trial);
            var disable=B("ACTIVAR / BLOQUEAR CUENTA");disable.Click+=(s,e)=>ToggleAccount();actions.Controls.Add(disable);
            var delAccount=B("ELIMINAR CUENTA");delAccount.ForeColor=Color.FromArgb(255,130,130);delAccount.Click+=(s,e)=>DeleteAccount();actions.Controls.Add(delAccount);
            var del=B("ELIMINAR TIENDA DE RAÍZ");del.ForeColor=Color.FromArgb(255,100,100);del.Click+=(s,e)=>DeleteStore();actions.Controls.Add(del);
            var reset=B("⚠ VACIAR TODO");reset.ForeColor=Color.FromArgb(255,170,80);reset.Click+=(s,e)=>FactoryReset();actions.Controls.Add(reset);
            var audit=B("AUDITORÍA / SEGURIDAD");audit.Click+=(s,e)=>ShowAudit();actions.Controls.Add(audit);
            _status=L("Desconectado",10);_status.ForeColor=muted;_status.Padding=new Padding(20,9,0,0);actions.Controls.Add(_status);
            var tabs=new TabControl{Dock=DockStyle.Fill,Font=new Font("Segoe UI",10),Padding=new Point(14,6)};root.Controls.Add(tabs,0,3);var ts=new TabPage("TIENDAS"){BackColor=bg,ForeColor=text};var ta=new TabPage("CUENTAS / PRUEBAS"){BackColor=bg,ForeColor=text};tabs.TabPages.Add(ts);tabs.TabPages.Add(ta);
            _stores=Grid(new[]{"Store ID","Tienda","Categoría","Ciudad","Provincia","Activa","Vendedor","Actualizada","Logo"});ts.Controls.Add(_stores);_accounts=Grid(new[]{"ID","Nombre","Correo","Rol","Store ID","Activa","Prueba vence","Creada"});ta.Controls.Add(_accounts);
            _stores.CellDoubleClick+=(s,e)=>ToggleSelectedStore();_accounts.CellDoubleClick+=(s,e)=>AssignTrial();
        }
        private Label Stat(TableLayoutPanel p,string title,int col){var box=Card();var l=L(title,9);l.ForeColor=muted;var n=new Label{Text="—",AutoSize=true,ForeColor=text,Font=new Font("Segoe UI",24,FontStyle.Bold),Location=new Point(14,28)};box.Controls.Add(l);l.Location=new Point(14,10);box.Controls.Add(n);p.Controls.Add(box, col,0);return n;}
        private DataGridView Grid(string[] cols){var g=new DataGridView{Dock=DockStyle.Fill,BackgroundColor=bg,BorderStyle=BorderStyle.None,GridColor=line,EnableHeadersVisualStyles=false,AllowUserToAddRows=false,ReadOnly=true,SelectionMode=DataGridViewSelectionMode.FullRowSelect,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,RowHeadersVisible=false};g.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(24,31,41);g.ColumnHeadersDefaultCellStyle.ForeColor=green;g.DefaultCellStyle.BackColor=Color.FromArgb(12,16,22);g.DefaultCellStyle.ForeColor=text;g.DefaultCellStyle.SelectionBackColor=Color.FromArgb(31,60,42);g.DefaultCellStyle.SelectionForeColor=text;foreach(string c in cols)g.Columns.Add(c,c);return g;}
        private void RefreshAll(){try{_api.BaseUrl=_url.Text.Trim();_api.AdminKey=_key.Text;string o=_api.Overview();if(!o.StartsWith("OK|")){_status.Text="Error: "+o;return;}var p=o.Split('|');_storesCount.Text=Get(p,"stores");_accountsCount.Text=Get(p,"accounts");_activeCount.Text=Get(p,"activeStores");_status.Text="✓ Conectado · "+Get(p,"database");LoadStores();LoadAccounts();}catch(Exception ex){_status.Text="Error: "+ex.Message;}}
        private string Get(string[] parts,string key){foreach(string x in parts){string[] p=x.Split(new[]{'='},2);if(p.Length==2&&p[0]==key)return p[1];}return "0";}
        private void LoadStores(){_stores.Rows.Clear();string r=_api.Stores();if(!r.StartsWith("STORE|")){if(r.StartsWith("ERROR|"))_status.Text=r;return;}foreach(string line in r.Split(new[]{'\n'},StringSplitOptions.RemoveEmptyEntries)){string[] raw=line.Split('|');if(raw.Length>=10){string[] p=raw.Select(Unescape).ToArray();_stores.Rows.Add(p.Skip(1).ToArray());}}}
        private void LoadAccounts(){_accounts.Rows.Clear();string r=_api.Accounts();if(!r.StartsWith("ACCOUNT|")){if(r.StartsWith("ERROR|"))_status.Text=r;return;}foreach(string line in r.Split(new[]{'\n'},StringSplitOptions.RemoveEmptyEntries)){string[] raw=line.Split('|');if(raw.Length>=9){string[] p=raw.Select(Unescape).ToArray();_accounts.Rows.Add(p.Skip(1).ToArray());}}}
        private string Unescape(string s){try{return Uri.UnescapeDataString(s??"");}catch{return s??"";}}
        private string Cell(DataGridView g,string col){if(g.SelectedRows.Count==0)return "";return Convert.ToString(g.SelectedRows[0].Cells[col].Value??"");}
        private void CreateStoreDialog(){using(var f=new Form{Text="Nueva tienda · Super Admin",Width=560,Height=500,StartPosition=FormStartPosition.CenterParent,BackColor=bg,ForeColor=text,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false}){var p=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(22),ColumnCount=2,RowCount=7};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,150));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));f.Controls.Add(p);_newStoreName=T();_newEmail=T();_newPassword=T();_newPassword.UseSystemPasswordChar=true;_newOwner=T();_newCategory=T();_trialDays=T();_trialDays.Text="30";AddField(p,"Nombre de tienda",_newStoreName,0);AddField(p,"Correo vendedor",_newEmail,1);AddField(p,"Contraseña",_newPassword,2);AddField(p,"Nombre propietario",_newOwner,3);AddField(p,"Categoría",_newCategory,4);AddField(p,"Días de prueba",_trialDays,5);var ok=B("CREAR TIENDA");ok.BackColor=Color.FromArgb(40,120,70);ok.Click+=(s,e)=>{var d=new Dictionary<string,string>{{"name",_newStoreName.Text},{"email",_newEmail.Text},{"password",_newPassword.Text},{"ownerName",_newOwner.Text},{"category",_newCategory.Text},{"trialDays",_trialDays.Text}};string r=_api.CreateStore(d);MessageBox.Show(r,"NexoMarket",MessageBoxButtons.OK,r.StartsWith("OK|")?MessageBoxIcon.Information:MessageBoxIcon.Error);if(r.StartsWith("OK|")){f.Close();RefreshAll();}};p.Controls.Add(ok,1,6);f.ShowDialog(this);}}
        private void AddField(TableLayoutPanel p,string label,Control c,int row){p.Controls.Add(L(label,9),0,row);p.Controls.Add(c,1,row);}
        private void AssignTrial(){string email=Cell(_accounts,"Correo");if(email.Length==0){MessageBox.Show("Seleccioná una cuenta.");return;}string raw=Prompt("Días de prueba para "+email,"30");int d;if(!int.TryParse(raw,out d)||d<0){MessageBox.Show("Cantidad de días inválida.");return;}string r=_api.SetTrial(email,d);MessageBox.Show(r,"NexoMarket");if(r.StartsWith("OK|"))RefreshAll();}
        private void ToggleAccount(){string email=Cell(_accounts,"Correo");if(email.Length==0){MessageBox.Show("Seleccioná una cuenta.");return;}bool current=Cell(_accounts,"Activa")=="1";string r=_api.SetAccountActive(email,!current);MessageBox.Show(r,"NexoMarket");if(r.StartsWith("OK|"))RefreshAll();}
        private void DeleteAccount(){string email=Cell(_accounts,"Correo");if(email.Length==0){MessageBox.Show("Seleccioná una cuenta.");return;}if(MessageBox.Show("¿Eliminar definitivamente la cuenta "+email+"?\n\nSi es vendedor y tiene tienda asociada, se eliminará la tienda completa.","ELIMINAR CUENTA",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;string r=_api.DeleteAccount(email);MessageBox.Show(r,"NexoMarket");if(r.StartsWith("OK|"))RefreshAll();}
        private void DeleteStore(){string id=Cell(_stores,"Store ID");if(id.Length==0){MessageBox.Show("Seleccioná una tienda.");return;}if(MessageBox.Show("Esto elimina tienda, cuenta vendedora, dispositivos, productos, pedidos y medios asociados.\n\n¿Continuar?","ELIMINACIÓN DEFINITIVA",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;string r=_api.DeleteStore(id);MessageBox.Show(r,"NexoMarket");if(r.StartsWith("OK|"))RefreshAll();}
        private void ToggleSelectedStore(){string id=Cell(_stores,"Store ID");if(id.Length==0)return;bool current=Cell(_stores,"Activa")=="1";string r=_api.SetStoreActive(id,!current);MessageBox.Show(r,"NexoMarket");if(r.StartsWith("OK|"))RefreshAll();}
        private void FactoryReset(){if(MessageBox.Show("ATENCIÓN: esto vacía TODAS las tiendas, cuentas, dispositivos, emparejamientos y datos centrales.\n\nEsta acción no se puede deshacer.\n\n¿Querés dejar NexoMarket como recién instalado?","VACIAR TODA LA PLATAFORMA",MessageBoxButtons.YesNo,MessageBoxIcon.Stop)!=DialogResult.Yes)return;string r=_api.FactoryReset();MessageBox.Show(r,"NexoMarket");if(r.StartsWith("OK|"))RefreshAll();}
        private void ShowAudit(){try{string r=_api.Audit("",200);if(r.IndexOf("admin_unauthorized",StringComparison.OrdinalIgnoreCase)>=0){MessageBox.Show("No autorizado o clave incorrecta.","Auditoría");return;}using(var f=new Form{Text="NexoMarket · Auditoría",Width=1000,Height=650,StartPosition=FormStartPosition.CenterParent,BackColor=bg,ForeColor=text}){var t=new TextBox{Dock=DockStyle.Fill,Multiline=true,ScrollBars=ScrollBars.Both,ReadOnly=true,BackColor=Color.FromArgb(8,11,16),ForeColor=text,Font=new Font("Consolas",9),Text=r};f.Controls.Add(t);f.ShowDialog(this);}}catch(Exception ex){MessageBox.Show(ex.Message,"Auditoría");}}
        private string Prompt(string title,string value){using(var f=new Form{Text=title,Width=420,Height=160,StartPosition=FormStartPosition.CenterParent,BackColor=bg,ForeColor=text,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){var t=T(350);t.Text=value;t.Location=new Point(25,25);f.Controls.Add(t);var ok=B("ACEPTAR");ok.Location=new Point(25,70);ok.DialogResult=DialogResult.OK;f.Controls.Add(ok);f.AcceptButton=ok;return f.ShowDialog(this)==DialogResult.OK?t.Text:value;}}
    }
}
